name       : rclone-browser
version    : 1.8.0
release    : 2
source     :
    - https://github.com/kapitainsky/RcloneBrowser/archive/1.8.0.tar.gz : 5f8242a011b85477749127b7e94e874035c431c2fa6df817e5603ed891604beb
license    : MIT
component  : network.util
summary    : Simple GUI for rclone
description: |
    Simple GUI for rclone. It supports Google Drive, Amazon Drive, Dropbox, One Drive, etc.
homepage   : https://github.com/kapitainsky/RcloneBrowser
builddeps  :
    - pkgconfig(Qt5Widgets)
rundeps    :
    - rclone
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
