name       : rclone-browser
version    : 1.7.0
release    : 1
source     :
    - https://github.com/kapitainsky/RcloneBrowser/archive/1.7.0.tar.gz : add7eb35fa521e87eddf9cfb36ddd11983f6fc78f520c3a887d353b574e3f083
license    : MIT
component  : network.util
summary    : Simple GUI for rclone
description: |
    Simple GUI for rclone. It supports Google Drive, Amazon Drive, Dropbox, One Drive, etc.
homepage   : https://github.com/kapitainsky/RcloneBrowser
builddeps  :
    - pkgconfig(Qt5Widgets)
rundeps    :
    - rclone
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
